[package]
name = "bolt-nn"
version.workspace = true
edition.workspace = true

[dependencies]
bolt-autodiff = { path = "../bolt-autodiff" }
bolt-core = { path = "../bolt-core" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
bolt-cpu = { path = "../bolt-cpu" }
bincode.workspace = true
