[package]
name = "bolt-examples"
version.workspace = true
edition.workspace = true

[dependencies]
bolt-autodiff = { path = "../bolt-autodiff" }
bolt-cpu = { path = "../bolt-cpu" }
bolt-data = { path = "../bolt-data" }
bolt-datasets = { path = "../bolt-datasets" }
bolt-nn = { path = "../bolt-nn" }
bolt-optim = { path = "../bolt-optim" }

